name: moe_wifi
description: "MoE Wi-Fi GUI client."
publish_to: "none"

version: 1.0.3+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.5
  logger: ^2.5.0
  http: ^1.2.2
  html: ^0.15.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
